server:
  port: ${application.port}
  tomcat:
    accept-count: 500
    threads:
      max: 500
      min-spare: 200
  datasource:
    enable: true
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 为 url
    url: ${datasource.${datasource.name}.url}
    # hikari 为 jdbc-url
    jdbc-url: ${datasource.${datasource.name}.url}
    username: ${datasource.${datasource.name}.username}
    password: ${datasource.${datasource.name}.password}
    driver-class-name: ${datasource.${datasource.name}.driver}